name: clipstrclub
description: Create video compilations of your favorite Twitch channel!
version: 0.0.1
apiVersion: v1
keywords:
  - twitch
  - clipping
  - clippers
  - video
  - editing
sources: []
home: https://github.com/insanity54/clippyclub-htmz
