apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app.kubernetes.io/name: web-pod
  ports:
    - name: web
      protocol: TCP
      port: 4000
      targetPort: 4000
status:
  loadBalancer: {}

